name: Run .NET Framework Console App

on:
  workflow_run:
    workflows: ["Build .NET Framework Console App"] # 引用 build.yml 的工作流程名稱
    branches: [ main ]
    types:
      - completed

jobs:
  run:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # 僅在 build.yml 成功時運行
  -name: Download Release Artifact
  uses: actions/download-artifact@v4
  with:
    name: hk-bus-release
    path: ./Release

-name: Extract Release Artifact
run: Expand-Archive -Path ./Release/hk-bus-release.zip -DestinationPath ./Release